# =============================================================================
# Harbor Configuration
# =============================================================================
# Private Docker Registry with vulnerability scanning
# Generated by Terraform - Do not edit manually
# =============================================================================

# The hostname for Harbor (used for docker login)
hostname: ${hostname}

# The protocol for accessing Harbor UI and API
http:
%{ if internal_tls ~}
  port: 80
%{ else ~}
  port: 8080
%{ endif ~}

%{ if internal_tls ~}
https:
  port: 443
  certificate: /etc/harbor/ssl/server.crt
  private_key: /etc/harbor/ssl/server.key
%{ endif ~}

# External URL for Harbor (used in notifications and links)
external_url: ${external_url}

# Harbor admin password
harbor_admin_password: ${admin_password}

# Database configuration
database:
  type: ${database_type}
  host: ${db_host}
  port: ${db_port}
  db_name: ${db_name}
  username: ${db_username}
  password: ${db_password}
  max_idle_conns: 50
  max_open_conns: 100
  conn_max_lifetime: 5m
  conn_max_idle_time: 0

# Storage configuration
storage_service:
  filesystem:
    rootdirectory: ${storage_path}
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
  cache:
    layerinfo: inmemory
  delete:
    enabled: true
  redirect:
    disable: false

# Data volume for Harbor internal data
data_volume: ${data_volume}

# Trivy vulnerability scanner
%{ if trivy_enabled ~}
trivy:
  ignore_unfixed: false
  skip_update: false
  offline_scan: false
  security_check: vuln
  insecure: false
  timeout: 5m0s
%{ endif ~}

# Job service configuration
jobservice:
  max_job_workers: 10
  logger_sweeper_duration: 1 # days

# Notification settings
notification:
  webhook_job_max_retry: 3
  webhook_job_http_client_timeout: 3 # seconds

# Log configuration
log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

# Internal communication (Docker network)
_version: 2.10.0

# Enable Chart Museum for Helm charts
chart:
  absolute_url: disabled

# Proxy configuration (if needed)
proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - trivy

# Cache layer configuration
cache:
  enabled: true
  expire_hours: 24

# Metrics for Prometheus
metric:
  enabled: true
  port: 9090
  path: /metrics

# Upload purging
upload_purging:
  enabled: true
  age: 168h
  interval: 24h
  dryrun: false

# Security settings
# CSRF key for protection against cross-site request forgery
core_secret: ${core_secret}
jobservice_secret: ${jobservice_secret}

# GC (Garbage Collection) settings
gc:
  # Delete untagged manifests when GC runs
  delete_untagged: true
  # Delete blobs older than this
  workers: 1

# Quota settings
quota:
  enabled: true

# Banner message (optional)
# banner_message: ""

# Max body size for uploads (0 = unlimited)
# Useful for large images
max_body_size: 0
