# =============================================================================
# Traefik Dynamic Configuration
# =============================================================================
# Routes for tooling services
# Generated by Terraform - Do not edit manually
# =============================================================================

http:
  routers:
%{ for name, route in routes ~}
    ${name}:
      rule: "Host(`${route.host}`)"
      entryPoints:
        - websecure
      service: ${name}-svc
%{ if route.tls ~}
      tls:
        certResolver: step-ca
%{ endif ~}

%{ endfor ~}

  services:
%{ for name, route in routes ~}
%{ if route.service != "api@internal" ~}
    ${name}-svc:
      loadBalancer:
        servers:
          - url: "http://${route.service}:${route.port}"
        passHostHeader: true

%{ endif ~}
%{ endfor ~}

  middlewares:
    secure-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customFrameOptionsValue: "SAMEORIGIN"

    rate-limit:
      rateLimit:
        average: 100
        burst: 50

    compress:
      compress: {}

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true

    modern:
      minVersion: VersionTLS13
