# =============================================================================
# Traefik Static Configuration
# =============================================================================
# Reverse proxy with ACME integration for Step-ca
# Generated by Terraform - Do not edit manually
# =============================================================================

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: ${log_level}
  format: json

accessLog:
  format: json
  filters:
    statusCodes:
      - "400-599"

api:
  dashboard: ${dashboard}
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: step-ca
%{ if acme_enabled ~}
        domains:
          - main: "${domain_suffix}"
            sans:
              - "*.${domain_suffix}"
%{ endif ~}

  metrics:
    address: ":${metrics_port}"

%{ if acme_enabled ~}
certificatesResolvers:
  step-ca:
    acme:
      email: "${acme_email}"
      storage: /certs/acme.json
      caServer: "${acme_server}"
      tlsChallenge: {}
      certificatesDuration: 2160
%{ endif ~}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: tooling_tooling
    watch: true

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

ping:
  entryPoint: web

serversTransport:
  insecureSkipVerify: ${insecure_skip}
