# =============================================================================
# Grafana OAuth2 Configuration for Authentik
# =============================================================================
# Add these environment variables to Grafana container/service
# Generated by Terraform - Do not edit manually
# =============================================================================

# Enable OAuth2 authentication
GF_AUTH_GENERIC_OAUTH_ENABLED=true
GF_AUTH_GENERIC_OAUTH_NAME=Authentik
GF_AUTH_GENERIC_OAUTH_ICON=signin

# Authentik OAuth2 endpoints
GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana
GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${grafana_client_secret}
GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
GF_AUTH_GENERIC_OAUTH_AUTH_URL=${authentik_url}/application/o/authorize/
GF_AUTH_GENERIC_OAUTH_TOKEN_URL=${authentik_url}/application/o/token/
GF_AUTH_GENERIC_OAUTH_API_URL=${authentik_url}/application/o/userinfo/
GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL=${authentik_url}/application/o/grafana/end-session/

# TLS configuration (trust internal CA)
GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=${tls_skip_verify}

# User attribute mapping
GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH=preferred_username
GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH=name
GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH=email

# Role mapping based on Authentik groups
GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'
GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT=false

# Allow OAuth sign-up (create users automatically)
GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true

# Auto-login (skip Grafana login page)
GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN=false

# Allow users to change their name/email
GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN=true

# Disable basic auth if only using SSO
# GF_AUTH_BASIC_ENABLED=false
# GF_AUTH_DISABLE_LOGIN_FORM=true

# Server configuration
GF_SERVER_ROOT_URL=${grafana_url}
