# =============================================================================
# Alertmanager Configuration
# Generated by Terraform - Do not edit manually
# =============================================================================

global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default'
  routes:
    - receiver: 'critical'
      match:
        severity: critical
      repeat_interval: 1h
    - receiver: 'warning'
      match:
        severity: warning
      repeat_interval: 4h

receivers:
  - name: 'default'
%{ if telegram_enabled && telegram_bot_token != "" && telegram_chat_id != "" }
    telegram_configs:
      - bot_token: '${telegram_bot_token}'
        chat_id: ${telegram_chat_id}
        parse_mode: 'HTML'
        message: |
          {{ if eq .Status "firing" }}🔴{{ else }}🟢{{ end }} <b>{{ .Status | toUpper }}</b>

          {{ range .Alerts }}
          <b>Alert:</b> {{ .Labels.alertname }}
          <b>Severity:</b> {{ .Labels.severity }}
          <b>Instance:</b> {{ .Labels.instance }}
          <b>Description:</b> {{ .Annotations.description }}
          {{ end }}
%{ else }
    # Telegram non configure - alertes loguees uniquement
%{ endif }

  - name: 'critical'
%{ if telegram_enabled && telegram_bot_token != "" && telegram_chat_id != "" }
    telegram_configs:
      - bot_token: '${telegram_bot_token}'
        chat_id: ${telegram_chat_id}
        parse_mode: 'HTML'
        message: |
          🚨 <b>CRITICAL ALERT</b> 🚨

          {{ range .Alerts }}
          <b>Alert:</b> {{ .Labels.alertname }}
          <b>Instance:</b> {{ .Labels.instance }}
          <b>Description:</b> {{ .Annotations.description }}
          <b>Started:</b> {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
%{ else }
    # Telegram non configure
%{ endif }

  - name: 'warning'
%{ if telegram_enabled && telegram_bot_token != "" && telegram_chat_id != "" }
    telegram_configs:
      - bot_token: '${telegram_bot_token}'
        chat_id: ${telegram_chat_id}
        parse_mode: 'HTML'
        message: |
          ⚠️ <b>WARNING</b>

          {{ range .Alerts }}
          <b>Alert:</b> {{ .Labels.alertname }}
          <b>Instance:</b> {{ .Labels.instance }}
          <b>Description:</b> {{ .Annotations.description }}
          {{ end }}
%{ else }
    # Telegram non configure
%{ endif }

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
