# =============================================================================
# Prometheus Configuration
# Generated by Terraform - Do not edit manually
# =============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: homelab
    datacenter: home

rule_files:
  - /etc/prometheus/alerts/*.yml

%{ if alertmanager_enabled }
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
%{ endif }

scrape_configs:
  # -------------------------------------------------------------------------
  # Prometheus self-monitoring
  # -------------------------------------------------------------------------
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'monitoring'

  # -------------------------------------------------------------------------
  # Node Exporter - Metriques systeme des hosts Proxmox
  # -------------------------------------------------------------------------
  - job_name: 'node-exporter'
    static_configs:
%{ for target in scrape_targets }
      - targets: ['${target.ip}:${target.port}']
        labels:
          instance: '${target.name}'
%{ if length(try(target.labels, {})) > 0 }
%{ for label_key, label_value in target.labels }
          ${label_key}: '${label_value}'
%{ endfor }
%{ endif }
%{ endfor }

  # -------------------------------------------------------------------------
  # Proxmox VE Exporter - Metriques Proxmox (VMs, containers, ressources)
  # -------------------------------------------------------------------------
%{ for node in proxmox_nodes }
  - job_name: 'pve-${node.name}'
    static_configs:
      - targets: ['pve-exporter:9221']
    params:
      target: ['${node.ip}']
      module: ['default']
    metrics_path: /pve
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
      - target_label: node
        replacement: '${node.name}'
%{ endfor }

  # -------------------------------------------------------------------------
  # Node Exporter sur la VM Monitoring elle-meme (optionnel)
  # -------------------------------------------------------------------------
  - job_name: 'monitoring-vm'
    static_configs:
      - targets: ['${monitoring_ip}:9100']
        labels:
          instance: 'monitoring-vm'
          role: 'monitoring'
