# =============================================================================
# Docker Compose - Tooling Stack
# =============================================================================
# Services: Step-ca (PKI), Harbor (Registry), Authentik (SSO), Traefik (Proxy)
# Generated by Terraform - Do not edit manually
# =============================================================================

networks:
  tooling:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
%{ for volume in volumes ~}
  ${volume}:
%{ endfor ~}

services:
%{ if step_ca_enabled ~}
  # ---------------------------------------------------------------------------
  # Step-ca - Internal PKI with ACME
  # ---------------------------------------------------------------------------
  step-ca:
    image: smallstep/step-ca:0.27.5@sha256:8f63def1db44ef34daa2914f38161358e87a4b14a22cf942fbbbe2f0fe73bf30
    container_name: step-ca
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      tooling:
        ipv4_address: 172.20.0.10
    ports:
      - "8443:8443"
      - "9290:9290"  # Prometheus metrics
    environment:
      - DOCKER_STEPCA_INIT_NAME=${step_ca_ca_name}
      - DOCKER_STEPCA_INIT_DNS_NAMES=${join(",", step_ca_dns_names)}
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_ACME=true
      - DOCKER_STEPCA_INIT_PASSWORD=${step_ca_password}
    volumes:
      - step-ca-data:/home/step
      - ./step-ca/ca.json:/home/step/config/ca.json:ro
      - ./step-ca/defaults.json:/home/step/config/defaults.json:ro
    healthcheck:
      test: ["CMD", "step", "ca", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.step-ca.rule=Host(`pki.${domain_suffix}`)"
      - "traefik.http.routers.step-ca.entrypoints=websecure"
      - "traefik.http.routers.step-ca.tls=true"
      - "traefik.http.services.step-ca.loadbalancer.server.port=8443"
      - "traefik.http.services.step-ca.loadbalancer.server.scheme=https"

%{ endif ~}
%{ if traefik_enabled ~}
  # ---------------------------------------------------------------------------
  # Traefik - Reverse Proxy with ACME
  # ---------------------------------------------------------------------------
  traefik:
    image: traefik:v3.3@sha256:2cd5cc75530c8d07ae0587c743d23eb30cae2436d07017a5ff78498b1a43d09f
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      tooling:
        ipv4_address: 172.20.0.2
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"  # Prometheus metrics
    environment:
      - LEGO_CA_CERTIFICATES=/certs/root_ca.crt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - traefik-certs:/certs
%{ if step_ca_enabled ~}
      - step-ca-data:/step-ca-data:ro
%{ endif ~}
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
%{ if step_ca_enabled ~}
      step-ca:
        condition: service_healthy
%{ endif ~}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${domain_suffix}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"

%{ endif ~}
%{ if harbor_enabled ~}
  # ---------------------------------------------------------------------------
  # Harbor - Docker Registry
  # ---------------------------------------------------------------------------
  harbor-db:
    image: goharbor/harbor-db:v2.12.2@sha256:ccdab9b3aac14b5415fc2f379339ed02866f51bed994c3d6214aa7fd9f1d4c08
    container_name: harbor-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    networks:
      - tooling
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${harbor_db_password}
    volumes:
      - harbor-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  harbor-registry:
    image: goharbor/registry-photon:v2.12.2@sha256:9709f31a872f1f1f425f36dd0c409b5d03272d166c5228f26e37d8a34af75a27
    container_name: harbor-registry
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - tooling
    volumes:
      - harbor-data:/storage
    depends_on:
      harbor-db:
        condition: service_healthy

  harbor-core:
    image: goharbor/harbor-core:v2.12.2@sha256:bba1623fccd533eed292c367fe217a15424219a5b905264a1542cc8cf0bdce96
    container_name: harbor-core
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      tooling:
        ipv4_address: 172.20.0.20
    environment:
      - CORE_SECRET=${harbor_core_secret}
      - HARBOR_ADMIN_PASSWORD=${harbor_admin_password}
      - DATABASE_TYPE=postgresql
      - POSTGRESQL_HOST=harbor-db
      - POSTGRESQL_DATABASE=registry
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=${harbor_db_password}
      - REGISTRY_URL=http://harbor-registry:5000
    volumes:
      - harbor-data:/data
    depends_on:
      harbor-db:
        condition: service_healthy
      harbor-registry:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v2.0/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.harbor.rule=Host(`registry.${domain_suffix}`)"
      - "traefik.http.routers.harbor.entrypoints=websecure"
      - "traefik.http.routers.harbor.tls=true"
      - "traefik.http.services.harbor.loadbalancer.server.port=8080"

  harbor-portal:
    image: goharbor/harbor-portal:v2.12.2@sha256:edddb228f106735683b8d287e9db99a18ff06dbc6819b98e483365b58f7b4a99
    container_name: harbor-portal
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - tooling
    depends_on:
      - harbor-core

  harbor-jobservice:
    image: goharbor/harbor-jobservice:v2.12.2@sha256:6afc108c165604e64106058f8420c849496865a7afec6b5f3ac0312b9a692881
    container_name: harbor-jobservice
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - tooling
    environment:
      - CORE_SECRET=${harbor_core_secret}
    depends_on:
      harbor-core:
        condition: service_healthy

%{ if harbor_trivy_enabled ~}
  harbor-trivy:
    image: goharbor/trivy-adapter-photon:v2.12.2@sha256:7fb1a0356a6b420dc6e63e3b2b1a12bee298be5d6cb7ecd7299caf43ede996af
    container_name: harbor-trivy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - tooling
    environment:
      - SCANNER_TRIVY_CACHE_DIR=/home/scanner/.cache/trivy
    volumes:
      - harbor-data:/home/scanner/.cache
    depends_on:
      - harbor-core

%{ endif ~}
%{ endif ~}
%{ if authentik_enabled ~}
  # ---------------------------------------------------------------------------
  # Authentik - SSO Provider
  # ---------------------------------------------------------------------------
  authentik-db:
    image: postgres:15-alpine@sha256:1d1095b0503145be79c79239372aefadfacf6b7c33c9245bbf99ce4b6b89c737
    container_name: authentik-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    networks:
      - tooling
    environment:
      - POSTGRES_USER=authentik
      - POSTGRES_PASSWORD=${authentik_pg_password}
      - POSTGRES_DB=authentik
    volumes:
      - authentik-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authentik"]
      interval: 10s
      timeout: 5s
      retries: 5

  authentik-redis:
    image: redis:7-alpine@sha256:02f2cc4882f8bf87c79a220ac958f58c700bdec0dfb9b9ea61b62fb0e8f1bfcf
    container_name: authentik-redis
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    networks:
      - tooling
    volumes:
      - authentik-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  authentik-server:
    image: ghcr.io/goauthentik/server:2025.2@sha256:36233579415aa2e2e52a6b0c45736cb871fe71460bfe0cf95d83f67528fb1182
    container_name: authentik-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      tooling:
        ipv4_address: 172.20.0.30
    command: server
    environment:
      - AUTHENTIK_SECRET_KEY=${authentik_secret_key}
      - AUTHENTIK_REDIS__HOST=authentik-redis
      - AUTHENTIK_POSTGRESQL__HOST=authentik-db
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${authentik_pg_password}
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_BOOTSTRAP_PASSWORD=${authentik_bootstrap_password}
      - AUTHENTIK_BOOTSTRAP_EMAIL=${authentik_bootstrap_email}
    volumes:
      - ./authentik/media:/media
      - ./authentik/templates:/templates
    depends_on:
      authentik-db:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ak", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`auth.${domain_suffix}`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls=true"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"

  authentik-worker:
    image: ghcr.io/goauthentik/server:2025.2@sha256:36233579415aa2e2e52a6b0c45736cb871fe71460bfe0cf95d83f67528fb1182
    container_name: authentik-worker
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - tooling
    command: worker
    environment:
      - AUTHENTIK_SECRET_KEY=${authentik_secret_key}
      - AUTHENTIK_REDIS__HOST=authentik-redis
      - AUTHENTIK_POSTGRESQL__HOST=authentik-db
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${authentik_pg_password}
      - AUTHENTIK_POSTGRESQL__NAME=authentik
    volumes:
      - ./authentik/media:/media
      - ./authentik/templates:/templates
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      authentik-db:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy

%{ endif ~}
