# =============================================================================
# Authentik Blueprint - Grafana OAuth2 Provider
# =============================================================================
# Configures Authentik as OAuth2 provider for Grafana
# Generated by Terraform - Do not edit manually
# =============================================================================

version: 1
metadata:
  name: Grafana OAuth2 Integration
  labels:
    blueprints.goauthentik.io/description: OAuth2 provider for Grafana monitoring

entries:
  # ---------------------------------------------------------------------------
  # OAuth2 Provider for Grafana
  # ---------------------------------------------------------------------------
  - model: authentik_providers_oauth2.oauth2provider
    id: provider-grafana
    identifiers:
      name: grafana
    attrs:
      name: Grafana
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      client_type: confidential
      client_id: grafana
      client_secret: ${grafana_client_secret}
      redirect_uris: |
        ${grafana_redirect_uri}
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
      sub_mode: hashed_user_id
      include_claims_in_id_token: true
      issuer_mode: per_provider
      access_token_validity: hours=1
      refresh_token_validity: days=30

  # ---------------------------------------------------------------------------
  # Application for Grafana
  # ---------------------------------------------------------------------------
  - model: authentik_core.application
    id: app-grafana
    identifiers:
      slug: grafana
    attrs:
      name: Grafana
      slug: grafana
      provider: !KeyOf provider-grafana
      policy_engine_mode: any
      meta_launch_url: ${grafana_url}
      meta_description: Grafana Monitoring Dashboard
      meta_publisher: Homelab
      open_in_new_tab: true
      icon: https://grafana.com/static/assets/img/fav32.png

  # ---------------------------------------------------------------------------
  # Group for Grafana Admins
  # ---------------------------------------------------------------------------
  - model: authentik_core.group
    id: group-grafana-admins
    identifiers:
      name: Grafana Admins
    attrs:
      name: Grafana Admins
      is_superuser: false
      attributes:
        grafana_role: Admin

  # ---------------------------------------------------------------------------
  # Group for Grafana Editors
  # ---------------------------------------------------------------------------
  - model: authentik_core.group
    id: group-grafana-editors
    identifiers:
      name: Grafana Editors
    attrs:
      name: Grafana Editors
      is_superuser: false
      attributes:
        grafana_role: Editor

  # ---------------------------------------------------------------------------
  # Group for Grafana Viewers
  # ---------------------------------------------------------------------------
  - model: authentik_core.group
    id: group-grafana-viewers
    identifiers:
      name: Grafana Viewers
    attrs:
      name: Grafana Viewers
      is_superuser: false
      attributes:
        grafana_role: Viewer

  # ---------------------------------------------------------------------------
  # Policy to bind groups to Grafana application
  # ---------------------------------------------------------------------------
  - model: authentik_policies_expression.expressionpolicy
    id: policy-grafana-access
    identifiers:
      name: grafana-access-policy
    attrs:
      name: Grafana Access Policy
      expression: |
        # Allow all authenticated users to access Grafana
        return True
