# =============================================================================
# Authentik Blueprint - Harbor OIDC Provider
# =============================================================================
# Configures Authentik as OIDC provider for Harbor Registry
# Generated by Terraform - Do not edit manually
# =============================================================================

version: 1
metadata:
  name: Harbor OIDC Integration
  labels:
    blueprints.goauthentik.io/description: OIDC provider for Harbor container registry

entries:
  # ---------------------------------------------------------------------------
  # OIDC Provider for Harbor
  # ---------------------------------------------------------------------------
  - model: authentik_providers_oauth2.oauth2provider
    id: provider-harbor
    identifiers:
      name: harbor
    attrs:
      name: Harbor Registry
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      client_type: confidential
      client_id: harbor
      client_secret: ${harbor_client_secret}
      redirect_uris: |
        ${harbor_redirect_uri}
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
        - !KeyOf scope-mapping-harbor-groups
      sub_mode: hashed_user_id
      include_claims_in_id_token: true
      issuer_mode: per_provider
      access_token_validity: hours=1
      refresh_token_validity: days=30

  # ---------------------------------------------------------------------------
  # Custom Scope Mapping for Harbor Groups
  # ---------------------------------------------------------------------------
  - model: authentik_providers_oauth2.scopemapping
    id: scope-mapping-harbor-groups
    identifiers:
      scope_name: groups
    attrs:
      name: Harbor Groups
      scope_name: groups
      description: Groups claim for Harbor OIDC
      expression: |
        # Return user's groups for Harbor
        groups = []
        for group in user.ak_groups.all():
            groups.append(group.name)
        return {
            "groups": groups,
        }

  # ---------------------------------------------------------------------------
  # Application for Harbor
  # ---------------------------------------------------------------------------
  - model: authentik_core.application
    id: app-harbor
    identifiers:
      slug: harbor
    attrs:
      name: Harbor Registry
      slug: harbor
      provider: !KeyOf provider-harbor
      policy_engine_mode: any
      meta_launch_url: ${harbor_url}
      meta_description: Private Docker Container Registry
      meta_publisher: Homelab
      open_in_new_tab: true
      icon: https://goharbor.io/img/logos/harbor-icon-color.png

  # ---------------------------------------------------------------------------
  # Group for Harbor Admins
  # ---------------------------------------------------------------------------
  - model: authentik_core.group
    id: group-harbor-admins
    identifiers:
      name: Harbor Admins
    attrs:
      name: Harbor Admins
      is_superuser: false
      attributes:
        harbor_role: admin

  # ---------------------------------------------------------------------------
  # Group for Harbor Developers (push/pull)
  # ---------------------------------------------------------------------------
  - model: authentik_core.group
    id: group-harbor-developers
    identifiers:
      name: Harbor Developers
    attrs:
      name: Harbor Developers
      is_superuser: false
      attributes:
        harbor_role: developer

  # ---------------------------------------------------------------------------
  # Group for Harbor Guests (pull only)
  # ---------------------------------------------------------------------------
  - model: authentik_core.group
    id: group-harbor-guests
    identifiers:
      name: Harbor Guests
    attrs:
      name: Harbor Guests
      is_superuser: false
      attributes:
        harbor_role: guest

  # ---------------------------------------------------------------------------
  # Policy for Harbor access
  # ---------------------------------------------------------------------------
  - model: authentik_policies_expression.expressionpolicy
    id: policy-harbor-access
    identifiers:
      name: harbor-access-policy
    attrs:
      name: Harbor Access Policy
      expression: |
        # Allow all authenticated users to access Harbor
        # Role mapping is handled by Harbor based on groups
        return True
