# =============================================================================
# Traefik Dynamic Configuration
# =============================================================================
# Routes and middlewares for homelab services
# Generated by Terraform - do not edit manually
# Domain: *.${domain_suffix}
# =============================================================================

http:
  # ---------------------------------------------------------------------------
  # Routers
  # ---------------------------------------------------------------------------

  routers:
    # Grafana - Main dashboard
    grafana:
      rule: "Host(`grafana.${domain_suffix}`)"
      service: grafana
      entryPoints:
        - web
%{ if tls_enabled }
        - websecure
      tls: {}
%{ endif }

    # Prometheus - Metrics database
    prometheus:
      rule: "Host(`prometheus.${domain_suffix}`)"
      service: prometheus
      entryPoints:
        - web
%{ if tls_enabled }
        - websecure
      tls: {}
%{ endif }

%{ if alertmanager_enabled }
    # Alertmanager - Alert routing
    alertmanager:
      rule: "Host(`alertmanager.${domain_suffix}`)"
      service: alertmanager
      entryPoints:
        - web
%{ if tls_enabled }
        - websecure
      tls: {}
%{ endif }
%{ endif }

%{ if loki_enabled }
    # Loki - Log aggregation
    loki:
      rule: "Host(`loki.${domain_suffix}`)"
      service: loki
      entryPoints:
        - web
%{ if tls_enabled }
        - websecure
      tls: {}
%{ endif }
%{ endif }

%{ if uptime_kuma_enabled }
    # Uptime Kuma - Status page
    uptime:
      rule: "Host(`uptime.${domain_suffix}`)"
      service: uptime
      entryPoints:
        - web
%{ if tls_enabled }
        - websecure
      tls: {}
%{ endif }
%{ endif }

    # Traefik Dashboard
    traefik-dashboard:
      rule: "Host(`traefik.${domain_suffix}`)"
      service: api@internal
      entryPoints:
        - web
%{ if tls_enabled }
        - websecure
      tls: {}
%{ endif }

  # ---------------------------------------------------------------------------
  # Middlewares (Security Headers - P2)
  # ---------------------------------------------------------------------------

  middlewares:
    secure-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customFrameOptionsValue: "SAMEORIGIN"
        contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"

    rate-limit:
      rateLimit:
        average: 100
        burst: 50

  # ---------------------------------------------------------------------------
  # Services
  # ---------------------------------------------------------------------------

  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

    prometheus:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"

%{ if alertmanager_enabled }
    alertmanager:
      loadBalancer:
        servers:
          - url: "http://alertmanager:9093"
%{ endif }

%{ if loki_enabled }
    loki:
      loadBalancer:
        servers:
          - url: "http://loki:3100"
%{ endif }

%{ if uptime_kuma_enabled }
    uptime:
      loadBalancer:
        servers:
          - url: "http://uptime-kuma:3001"
%{ endif }

%{ if tls_enabled }
# -----------------------------------------------------------------------------
# TLS Configuration
# -----------------------------------------------------------------------------

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/cert.pem
        keyFile: /etc/traefik/certs/key.pem
%{ endif }
