# =============================================================================
# Traefik Static Configuration
# =============================================================================
# Reverse proxy for homelab services with automatic routing
# Generated by Terraform - do not edit manually
# =============================================================================

# -----------------------------------------------------------------------------
# Global Configuration
# -----------------------------------------------------------------------------

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# -----------------------------------------------------------------------------
# API and Dashboard
# -----------------------------------------------------------------------------

api:
  dashboard: true
  insecure: true  # Dashboard accessible without auth on port 8080

# -----------------------------------------------------------------------------
# Entry Points
# -----------------------------------------------------------------------------

entryPoints:
  web:
    address: ":80"
%{ if tls_enabled }
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
%{ endif }

# -----------------------------------------------------------------------------
# Providers
# -----------------------------------------------------------------------------

providers:
  # Docker provider for automatic service discovery
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: monitoring
    watch: true

  # File provider for static routes
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------

log:
  level: INFO
  format: common

accessLog:
  format: common
  filters:
    statusCodes:
      - "400-599"
